In [1]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split, cross_val_score, RandomizedSearchCV, GridSearchCV
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, accuracy_score

In [2]:
df = pd.read_excel(
'asia index2.xlsx',
    header =1,
)

df = df.rename(columns={'Unnamed: 0':'Date'})
# print(type(df['Date']))
df

,Date,Indonesia,Laos,Malaysia,Philippines,Singapore,Thailand,Vietnam
0,2014-01-02,4327.265,1261.71,1852.95,5984.26,3174.65,833.29,504.51
1,2014-01-03,4257.663,1251.31,1834.74,5947.93,3131.47,829.89,505.37
2,2014-01-06,4202.809,1258.66,1829.18,5985.81,3123.82,837.68,509.10
3,2014-01-07,4175.806,1258.66,1825.11,5947.44,3120.88,861.63,510.12
4,2014-01-08,4200.593,1266.25,1831.30,5986.48,3150.65,859.35,513.90
5,2014-01-09,4201.218,1266.25,1828.21,5937.51,3145.41,860.00,516.98
6,2014-01-10,4254.971,1263.34,1826.61,5842.88,3143.87,858.25,518.94
7,2014-01-13,4390.771,1263.34,1834.97,5940.67,3135.49,880.70,521.11
8,2014-01-15,4441.594,1245.36,1824.03,5958.12,3143.25,871.02,526.68
9,2014-01-16,4412.489,1245.36,1813.01,5982.24,3140.44,888.02,533.54
10,2014-01-17,4412.228,1244.80,NaN,5987.09,3147.33,883.94,543.59
11,2014-01-20,4431.572,1235.13,1807.59,6005.60,3128.79,879.05,553.67
12,2014-01-21,4452.499,1235.13,1815.34,6019.24,3133.76,880.84,559.91
13,2014-01-22,4477.489,1238.78,1814.10,6139.86,3133.74,879.59,551.92
14,2014-01-23,4496.042,1231.42,1808.31,6170.05,3100.24,894.11,553.55
15,2014-01-24,4437.343,1220.78,1802.57,6191.50,3075.99,898.88,560.19
16,2014-01-27,4322.780,1257.54,1778.88,6081.61,3042.43,878.55,556.52
17,2014-01-28,4341.651,1245.62,1781.25,6022.81,3062.41,865.18,NaN
18,2014-01-29,4417.349,1246.89,1789.23,6069.84,3047.93,863.61,NaN
19,2014-01-30,4418.757,1239.47,1804.03,6041.19,3027.22,857.50,NaN
20,2014-02-03,4386.259,1240.74,NaN,6015.30,2990.95,879.72,NaN
21,2014-02-04,4352.256,1239.77,1778.83,5886.01,2965.80,865.23,NaN
22,2014-02-05,4384.310,1241.33,1785.88,5908.41,2960.09,867.11,NaN
23,2014-02-06,4424.709,1246.49,1797.90,5914.59,2988.27,878.27,554.68
24,2014-02-07,4466.665,1247.46,1808.59,6011.14,3013.14,879.69,549.76
25,2014-02-10,4450.748,1247.46,1816.14,6042.25,3017.20,874.88,555.90
26,2014-02-11,4470.190,1249.14,1824.17,6106.03,3029.10,879.09,553.90
27,2014-02-12,4496.286,1255.91,1825.64,6112.31,3035.45,892.57,564.25
28,2014-02-13,4491.660,1257.85,1817.15,6101.72,3039.90,890.01,570.18
29,2014-02-14,4508.044,1257.85,1819.37,6113.66,3038.71,NaN,572.22
...,...,...,...,...,...,...,...,...
1578,2019-11-19,6152.090,690.75,1605.31,7912.14,3238.87,1084.27,1008.35
1579,2019-11-20,6155.109,682.75,1601.14,7898.06,3229.78,1075.77,1000.56
1580,2019-11-21,6117.364,675.72,1592.19,7818.89,3192.21,1073.10,987.89
1581,2019-11-22,6100.242,675.72,1596.84,7824.59,3225.65,1077.51,977.78
1582,2019-11-25,6070.762,672.17,1591.35,7771.62,3220.63,1089.67,976.35
1583,2019-11-26,6026.188,659.21,1583.87,7707.80,3207.85,1083.70,976.79
1584,2019-11-27,6023.039,659.55,1587.18,7836.89,3215.53,1084.13,978.17
1585,2019-11-28,5953.060,659.34,1583.77,7768.66,3200.61,1077.30,970.39
1586,2019-11-29,6011.830,671.73,1561.74,7738.96,3193.92,1070.23,970.75
1587,2019-12-02,6130.055,NaN,1570.55,7877.19,3187.97,1054.88,959.31
1588,2019-12-03,6133.896,659.74,1562.27,7855.18,3173.08,1054.28,953.43
1589,2019-12-04,6112.879,671.45,1560.93,7815.93,3159.79,1053.40,965.90
1590,2019-12-05,6152.117,670.11,1563.58,7790.91,3174.19,NaN,963.27
1591,2019-12-06,6186.868,663.99,1568.44,7801.72,3194.71,1048.76,963.56
1592,2019-12-09,6193.791,663.99,1562.71,7779.80,3179.82,1047.02,966.06
1593,2019-12-10,6183.505,642.95,1561.79,7736.18,3162.89,NaN,960.30
1594,2019-12-11,6180.099,661.72,1563.19,7786.41,3172.90,1048.85,961.78
1595,2019-12-12,6139.397,674.05,1567.34,7741.07,3194.67,1057.87,968.17
1596,2019-12-13,6197.318,669.27,1571.16,7877.63,3214.05,1066.63,966.18
1597,2019-12-16,6211.592,678.87,1569.35,7701.60,3206.09,1048.08,961.47
1598,2019-12-17,6244.352,679.11,1576.95,7730.45,3200.80,1049.84,954.03
1599,2019-12-18,6287.250,678.69,1599.11,7733.67,3209.54,1062.62,951.13
1600,2019-12-19,6249.930,671.49,1595.72,7653.94,3207.42,1068.39,952.26
1601,2019-12-20,6284.372,685.47,1610.18,7773.12,3212.39,1067.62,956.41
1602,2019-12-23,6305.910,727.80,1614.18,7872.60,3214.00,1069.53,959.43
1603,2019-12-24,NaN,724.14,1604.23,NaN,3221.67,1065.23,958.88
1604,2019-12-25,NaN,724.14,NaN,NaN,3221.67,1067.99,960.92
1605,2019-12-26,6319.443,728.11,1603.55,7842.28,3222.99,1070.74,958.59
1606,2019-12-27,6329.314,NaN,1610.61,7815.26,3226.53,1068.72,963.51
1607,2019-12-30,6299.539,NaN,1615.67,NaN,3222.44,1068.50,965.03

In [3]:
df.isnull().sum()

Date             0
Indonesia      133
Laos           136
Malaysia       139
Philippines    167
Singapore      100
Thailand       172
Vietnam        128
dtype: int64

In [4]:
df = df.fillna(method='ffill')
# df = df.dropna()
df.isnull().sum()

Date           0
Indonesia      0
Laos           0
Malaysia       0
Philippines    0
Singapore      0
Thailand       0
Vietnam        0
dtype: int64

In [5]:
stat = df.describe()
stat

,Indonesia,Laos,Malaysia,Philippines,Singapore,Thailand,Vietnam
count,1608.000000,1608.000000,1608.000000,1608.000000,1608.000000,1608.000000,1608.00000
mean,5536.136718,1063.564384,1728.011381,7516.936692,3169.920498,1021.312320,769.91732
std,637.137830,222.354872,85.417807,555.238089,217.540822,93.383757,186.45646
min,4120.503000,642.950000,1532.140000,5842.880000,2532.700000,761.750000,504.51000
25%,4986.962500,873.535000,1661.800000,7146.330000,3045.862500,950.375000,590.72000
50%,5520.982500,1027.230000,1718.265000,7581.790000,3212.100000,1028.055000,714.81500
75%,6076.733500,1249.860000,1799.170000,7906.707500,3321.787500,1091.550000,962.86250
max,6689.287000,1566.920000,1895.180000,9058.620000,3615.280000,1206.310000,1204.33000

In [6]:
stat.loc['std', 'Indonesia':'Vietnam']

Indonesia      637.137830
Laos           222.354872
Malaysia        85.417807
Philippines    555.238089
Singapore      217.540822
Thailand        93.383757
Vietnam        186.456460
Name: std, dtype: float64

In [7]:
df2 = pd.read_excel(
'kursasean2.xlsx'
)


df2 = df2.fillna(method='ffill')
# df = df.dropna()
df2.isnull().sum()
# df2

Date           0
Indonesia      0
Laos           0
Malaysia       0
Philippines    0
Singapore      0
Thailand       0
Vietnam        0
dtype: int64

In [8]:
df2

,Date,Indonesia,Laos,Malaysia,Philippines,Singapore,Thailand,Vietnam
0,2014-01-02,12150.0,8000.00,3.2850,44.470,1.2672,32.95,21060.0
1,2014-01-03,12160.0,8021.00,3.2850,44.690,1.2670,32.99,21075.0
2,2014-01-06,12170.0,8021.00,3.2835,44.540,1.2677,33.05,21080.0
3,2014-01-07,12230.0,8003.00,3.2830,44.800,1.2710,33.05,21075.0
4,2014-01-08,12225.0,8018.00,3.2710,44.680,1.2730,33.03,21080.0
5,2014-01-09,12185.0,8015.00,3.2750,44.600,1.2704,32.99,21075.0
6,2014-01-10,12155.0,8013.00,3.2680,44.550,1.2635,32.96,21072.0
7,2014-01-13,12045.0,8009.00,3.2600,44.590,1.2646,32.95,21060.0
8,2014-01-15,12080.0,7991.00,3.2860,45.100,1.2726,32.85,21070.0
9,2014-01-16,12115.0,8005.00,3.2960,45.130,1.2713,32.74,21080.0
10,2014-01-17,12085.0,8000.00,3.2960,45.050,1.2760,32.81,21070.0
11,2014-01-20,12105.0,8015.00,3.3150,45.130,1.2762,32.79,21070.0
12,2014-01-21,12125.0,8018.00,3.3230,45.400,1.2780,32.85,21075.0
13,2014-01-22,12135.0,8015.00,3.3220,45.280,1.2788,32.90,21070.0
14,2014-01-23,12160.0,8010.00,3.3290,45.300,1.2782,32.86,21065.0
15,2014-01-24,12175.0,7995.00,3.3330,45.420,1.2785,32.80,21060.0
16,2014-01-27,12225.0,7991.00,3.3435,45.350,1.2763,32.89,21035.0
17,2014-01-28,12185.0,7991.00,3.3340,45.210,1.2751,32.89,21035.0
18,2014-01-29,12160.0,8011.00,3.3365,45.230,1.2767,32.93,21035.0
19,2014-01-30,12205.0,8009.00,3.3450,45.310,1.2750,32.99,21035.0
20,2014-02-03,12235.0,8020.00,3.3450,45.400,1.2757,32.92,21035.0
21,2014-02-04,12195.0,8010.00,3.3235,45.275,1.2684,32.73,21035.0
22,2014-02-05,12188.0,8007.00,3.3125,45.320,1.2679,32.74,21075.0
23,2014-02-06,12175.0,8006.00,3.3215,45.180,1.2683,32.77,21080.0
24,2014-02-07,12155.0,7990.00,3.3290,44.950,1.2680,32.80,21085.0
25,2014-02-10,12170.0,8011.00,3.3350,44.990,1.2703,32.79,21085.0
26,2014-02-11,12140.0,8010.00,3.3265,44.940,1.2673,32.71,21090.0
27,2014-02-12,12080.0,8011.00,3.3210,44.800,1.2657,32.51,21080.0
28,2014-02-13,11970.0,8001.00,3.3235,44.880,1.2646,32.54,21085.0
29,2014-02-14,11820.0,8001.00,3.3065,44.580,1.2590,32.29,21070.0
...,...,...,...,...,...,...,...,...
1578,2019-11-19,14085.0,8823.45,4.1560,50.990,1.3615,30.18,23200.0
1579,2019-11-20,14090.0,8824.45,4.1640,50.930,1.3621,30.18,23199.0
1580,2019-11-21,14080.0,8840.00,4.1680,50.820,1.3628,30.20,23193.0
1581,2019-11-22,14080.0,8823.45,4.1700,50.910,1.3642,30.19,23195.0
1582,2019-11-25,14070.0,8813.48,4.1770,50.810,1.3650,30.21,23197.0
1583,2019-11-26,14080.0,8813.48,4.1810,50.830,1.3645,30.22,23190.0
1584,2019-11-27,14090.0,8860.00,4.1700,50.860,1.3658,30.22,23200.0
1585,2019-11-28,14085.0,8857.00,4.1720,50.810,1.3657,30.23,23200.0
1586,2019-11-29,14100.0,8860.00,4.1750,50.840,1.3677,30.19,23179.0
1587,2019-12-02,14120.0,8831.43,4.1780,51.040,1.3667,30.27,23175.0
1588,2019-12-03,14100.0,8858.00,4.1730,51.080,1.3638,30.26,23170.0
1589,2019-12-04,14100.0,8832.42,4.1750,50.960,1.3628,30.30,23170.0
1590,2019-12-05,14060.0,8833.42,4.1680,50.790,1.3606,30.36,23167.0
1591,2019-12-06,14035.0,8855.00,4.1580,50.800,1.3592,30.35,23175.0
1592,2019-12-09,14010.0,8871.00,4.1590,50.810,1.3599,30.30,23170.0
1593,2019-12-10,14005.0,8837.41,4.1630,50.740,1.3585,30.27,23170.0
1594,2019-12-11,14030.0,8843.39,4.1630,50.770,1.3571,30.22,23175.0
1595,2019-12-12,14020.0,8839.40,4.1580,50.580,1.3517,30.16,23169.0
1596,2019-12-13,13980.0,8838.41,4.1335,50.600,1.3535,30.19,23173.0
1597,2019-12-16,14000.0,8833.42,4.1400,50.540,1.3559,30.20,23176.0
1598,2019-12-17,13985.0,8860.00,4.1410,50.570,1.3553,30.24,23176.0
1599,2019-12-18,13970.0,8855.00,4.1370,50.650,1.3553,30.22,23173.0
1600,2019-12-19,13980.0,8838.41,4.1400,50.590,1.3548,30.18,23169.0
1601,2019-12-20,13970.0,8865.00,4.1380,50.760,1.3546,30.19,23175.0
1602,2019-12-23,13960.0,8853.36,4.1410,50.820,1.3557,30.15,23173.0
1603,2019-12-24,13960.0,8875.00,4.1350,50.800,1.3550,30.13,23176.0
1604,2019-12-25,13960.0,8875.00,4.1350,50.820,1.3550,30.15,23173.0
1605,2019-12-26,13950.0,8843.39,4.1310,50.700,1.3538,30.10,23174.0
1606,2019-12-27,13945.0,8875.00,4.1260,50.810,1.3519,30.13,23171.0
1607,2019-12-30,13920.0,8870.00,4.1045,50.780,1.3486,29.94,23170.0

In [9]:
dfkali = df.loc[0:, 'Indonesia':]
df2kali = df2.loc[0:, 'Indonesia':]
dfgab = dfkali / df2kali
dfgab

dfgab.to_excel("dfgab.xlsx")

In [10]:
dflaos = dfgab.loc[0:, ['Laos']]
# df.iloc[0:2, 0:2]
# df[['Date', 'Indonesia']][0:2]
dflaos

          Laos
0     0.157714
1     0.156004
2     0.156921
3     0.157274
4     0.157926
5     0.157985
6     0.157661
7     0.157740
8     0.155845
9     0.155573
10    0.155600
11    0.154102
12    0.154045
13    0.154558
14    0.153735
15    0.152693
16    0.157370
17    0.155878
18    0.155647
19    0.154760
20    0.154706
21    0.154778
22    0.155031
23    0.155694
24    0.156128
25    0.155718
26    0.155948
27    0.156773
28    0.157212
29    0.157212
...        ...
1578  0.078286
1579  0.077370
1580  0.076439
1581  0.076582
1582  0.076266
1583  0.074796
1584  0.074441
1585  0.074443
1586  0.075816
1587  0.076061
1588  0.074480
1589  0.076021
1590  0.075861
1591  0.074985
1592  0.074850
1593  0.072753
1594  0.074827
1595  0.076255
1596  0.075723
1597  0.076852
1598  0.076649
1599  0.076645
1600  0.075974
1601  0.077323
1602  0.082206
1603  0.081593
1604  0.081593
1605  0.082334
1606  0.082041
1607  0.082087

[1608 rows x 1 columns]

In [11]:
# a variable for prediction 'n' days out into the future
forecast_out = 1
## create another column (the target or dependent variable) shifted 'n' units up
dflaos['predictlaos']= dflaos[['Laos']].shift(-forecast_out)

dflaos

          Laos  predictlaos
0     0.157714     0.156004
1     0.156004     0.156921
2     0.156921     0.157274
3     0.157274     0.157926
4     0.157926     0.157985
5     0.157985     0.157661
6     0.157661     0.157740
7     0.157740     0.155845
8     0.155845     0.155573
9     0.155573     0.155600
10    0.155600     0.154102
11    0.154102     0.154045
12    0.154045     0.154558
13    0.154558     0.153735
14    0.153735     0.152693
15    0.152693     0.157370
16    0.157370     0.155878
17    0.155878     0.155647
18    0.155647     0.154760
19    0.154760     0.154706
20    0.154706     0.154778
21    0.154778     0.155031
22    0.155031     0.155694
23    0.155694     0.156128
24    0.156128     0.155718
25    0.155718     0.155948
26    0.155948     0.156773
27    0.156773     0.157212
28    0.157212     0.157212
29    0.157212     0.156817
...        ...          ...
1578  0.078286     0.077370
1579  0.077370     0.076439
1580  0.076439     0.076582
1581  0.076582     0.076266
1582  0.076266     0.074796
1583  0.074796     0.074441
1584  0.074441     0.074443
1585  0.074443     0.075816
1586  0.075816     0.076061
1587  0.076061     0.074480
1588  0.074480     0.076021
1589  0.076021     0.075861
1590  0.075861     0.074985
1591  0.074985     0.074850
1592  0.074850     0.072753
1593  0.072753     0.074827
1594  0.074827     0.076255
1595  0.076255     0.075723
1596  0.075723     0.076852
1597  0.076852     0.076649
1598  0.076649     0.076645
1599  0.076645     0.075974
1600  0.075974     0.077323
1601  0.077323     0.082206
1602  0.082206     0.081593
1603  0.081593     0.081593
1604  0.081593     0.082334
1605  0.082334     0.082041
1606  0.082041     0.082087
1607  0.082087          NaN

[1608 rows x 2 columns]

In [12]:
## create the independent data set (x)
# convert the dataframe to a numpy array
xlaos = np.array(dflaos.drop(['predictlaos'], axis=1))

xlaos
#remove the 'n' rows
xlaos = xlaos[:-forecast_out]
xlaos
xlaosreshape = xlaos.reshape(-1)
xlaoslist = xlaos.tolist()
# xlaoslist
xlaosreshape

array([0.15771375, 0.15600424, 0.15692058, ..., 0.08159324, 0.08233381,
       0.08204056])

In [13]:
## create the dependent data set(y)
# convert dataframe to a numpy array (all of the values includeing the NaN's)

ylaos = np.array(dflaos['predictlaos'])
#get all of the y values except the last 'n' rows
ylaos = ylaos[:-forecast_out]
ylaos
ylaoslist = ylaos.tolist()
ylaoslist

[0.15600423887295847,
 0.15692058346839546,
 0.1572735224290891,
 0.15792591668745323,
 0.1579850280723643,
 0.15766130038687132,
 0.1577400424522412,
 0.1558453259917407,
 0.1555727670206121,
 0.1556,
 0.15410230817217718,
 0.1540446495385383,
 0.1545577043044292,
 0.15373533083645444,
 0.152692933083177,
 0.157369540733325,
 0.15587786259541983,
 0.15564723505180378,
 0.1547596453989262,
 0.1547057356608479,
 0.15477777777777776,
 0.15503059822655177,
 0.15569447914064452,
 0.1561276595744681,
 0.15571838721757583,
 0.15594756554307118,
 0.15677318686805644,
 0.15721159855018121,
 0.15721159855018121,
 0.15681670417604401,
 0.15599275271773086,
 0.1566140350877193,
 0.15760676268002505,
 0.1647734668335419,
 0.16063821799524466,
 0.15769173026398098,
 0.15769173026398098,
 0.16281691903391315,
 0.16276561131272682,
 0.16248217190041286,
 0.16167313227380803,
 0.1602227505944187,
 0.15984269662921347,
 0.1570943160524672,
 0.1570943160524672,
 0.1618051217988757,
 0.16105795653260055,
 0.16103784188834772,
 0.161360739722604,
 0.161360739722604,
 0.16101773226773228,
 0.16212564006494318,
 0.16123921470551458,
 0.16774157303370785,
 0.16601818408270022,
 0.1629273157960354,
 0.16296795111609924,
 0.16521614550890745,
 0.1655117815733699,
 0.16527531527032088,
 0.16500747943156321,
 0.1653579013116802,
 0.1653579013116802,
 0.16318301061836352,
 0.15881338995753186,
 0.15881338995753186,
 0.15663877092180864,
 0.15661920819283126,
 0.15663877092180864,
 0.1566583385384135,
 0.1561511642385755,
 0.15831901382144192,
 0.15835597656736883,
 0.1585559296670408,
 0.15646288209606987,
 0.1574501246882793,
 0.15859548459523512,
 0.15859548459523512,
 0.1585559296670408,
 0.15883747037545218,
 0.159039780521262,
 0.16125078017725628,
 0.1613514863852111,
 0.1630373599003736,
 0.16338068535825548,
 0.16555015576323986,
 0.16309936416905624,
 0.1630587062196186,
 0.1627896246414765,
 0.1598153922913808,
 0.16301122194513715,
 0.16102109599300962,
 0.16112165875593307,
 0.1598925134358205,
 0.1630753844230529,
 0.16208281522009452,
 0.16039470397202096,
 0.15995771144278606,
 0.15993781867926873,
 0.15981580584940883,
 0.15971641791044774,
 0.160296647139474,
 0.160578481486099,
 0.15960149439601493,
 0.1599800274622394,
 0.1594228137828088,
 0.16118675827607745,
 0.16094440974391006,
 0.16092430676992256,
 0.15985758900687072,
 0.16097892505299913,
 0.16081721771678104,
 0.16071695760598503,
 0.16085856697819315,
 0.16085856697819315,
 0.1621459762944479,
 0.16218442367601246,
 0.16451914681302232,
 0.16234677318686805,
 0.16246785669704156,
 0.1634340282112096,
 0.16443710260566013,
 0.16394825227018286,
 0.16425280199252804,
 0.16451914681302232,
 0.17207631874298543,
 0.17236123238118997,
 0.1722752773968333,
 0.1698840399002494,
 0.1688624173631034,
 0.1689045539613225,
 0.1688624173631034,
 0.1688624173631034,
 0.17099139543583988,
 0.1699688123752495,
 0.16894126449682006,
 0.17043158288636645,
 0.17094875950629598,
 0.17356866658351003,
 0.17537732318822502,
 0.17258955223880595,
 0.1741307596513076,
 0.1741307596513076,
 0.1742392523364486,
 0.17409668577124346,
 0.1742175429852978,
 0.17527968107636727,
 0.18175744733890067,
 0.17741617848685032,
 0.18037895786586886,
 0.17992022934064564,
 0.1789567493456313,
 0.17652293120638088,
 0.17626462534229523,
 0.17856502242152467,
 0.17652829718274743,
 0.1787972080269226,
 0.17644031896336904,
 0.17915991524367444,
 0.1779977558907867,
 0.17782364679471188,
 0.1779977558907867,
 0.17782364679471188,
 0.17758002241873208,
 0.17782364679471188,
 0.1792980264801399,
 0.1793204247345409,
 0.17750342593746107,
 0.17890870541282117,
 0.1787431421446384,
 0.1787431421446384,
 0.17807788317523715,
 0.17817546486958694,
 0.17890521858263794,
 0.17804214989400174,
 0.17670404984423677,
 0.17565103517086553,
 0.17190914747977598,
 0.17171044441678077,
 0.17203167872287353,
 0.17578247358607832,
 0.17507152630924244,
 0.17394602661360528,
 0.17394602661360528,
 0.1749844585353724,
 0.17474449832152184,
 0.17618774900398407,
 0.17625358076970982,
 0.17634143302180685,
 0.17747102081515642,
 0.17741645885286783,
 0.177294234839995,
 0.17717345287012826,
 0.1776379525593009,
 0.17856804290881875,
 0.1785235066716548,
 0.17868903579892728,
 0.178310928553647,
 0.17832336821126057,
 0.1761986045352604,
 0.17827895392278953,
 0.17396437912566945,
 0.17697512437810947,
 0.17701915899477483,
 0.17685447761194031,
 0.17579300908073145,
 0.1735841313269494,
 0.17589179104477612,
 0.17608928127331508,
 0.17721641791044776,
 0.17807701863354036,
 0.17925202240199128,
 0.1793504230960677,
 0.17593555610848471,
 0.17599054843924886,
 0.17827895392278953,
 0.17772936636374953,
 0.17768512756689483,
 0.17739260366081436,
 0.17715797335989045,
 0.1771254203512268,
 0.17669650627875172,
 0.1741947100459456,
 0.1745849408836341,
 0.17421340629274965,
 0.17423507462686566,
 0.1760390013662899,
 0.1759846134756173,
 0.17379019242706395,
 0.17293628120730342,
 0.17393784959602238,
 0.17363568680977787,
 0.17388220706757593,
 0.17438764114654426,
 0.17265541630475245,
 0.17448417132216015,
 0.17265962732919254,
 0.17302354399008674,
 0.17333126627806028,
 0.17408297213622292,
 0.17421241789565003,
 0.1741908302354399,
 0.1741908302354399,
 0.17547958803821814,
 0.17359791640828476,
 0.17403846153846153,
 0.1736663770634231,
 0.17382436611008037,
 0.17404205318491034,
 0.17445997773104047,
 0.17381482856789207,
 0.17348636307540416,
 0.1744589759407773,
 0.17435748673003335,
 0.1727874306839187,
 0.1739753086419753,
 0.17427937369005053,
 0.1744083898827884,
 0.17451604938271603,
 0.17351931860264166,
 0.17351931860264166,
 0.17375525339925835,
 0.1738674237748426,
 0.17309999999999998,
 0.17272592592592592,
 0.17291234567901234,
 0.17213456790123458,
 0.17356446637877854,
 0.17250864197530863,
 0.17021218850234393,
 0.17023318938926588,
 0.17250864197530863,
 0.17190987654320988,
 0.17495429841897234,
 0.1749962889658585,
 0.17338062924120912,
 0.17465061728395062,
 0.17251234567901233,
 0.17306198193739947,
 0.17473886138613862,
 0.17471723796559832,
 0.17484848484848486,
 0.17342486085343228,
 0.17567574257425744,
 0.17589356435643563,
 0.1761767983162065,
 0.17622985370691793,
 0.18364232673267325,
 0.1835741680069281,
 0.17548917748917747,
 0.17840864197530862,
 0.18263827160493826,
 0.18081061073411475,
 0.1794608266502159,
 0.18048130322102926,
 0.18052586100481421,
 0.17845432098765432,
 0.17818540920873965,
 0.17842768850432633,
 0.1792933909820877,
 0.18231244592757384,
 0.18231244592757384,
 0.19356639901173564,
 0.19159930787294524,
 0.19176049382716048,
 0.1909122373300371,
 0.19088864170065506,
 0.18392450495049503,
 0.18585818586808564,
 0.1875337210741245,
 0.18171534653465346,
 0.1882682323856613,
 0.19022249690976514,
 0.19019898652824127,
 0.19022249690976514,
 0.19019898652824127,
 0.19022249690976514,
 0.1814052651093808,
 0.18807316771721666,
 0.18123346928686193,
 0.18313419913419915,
 0.18313861386138613,
 0.18433539603960397,
 0.18130198019801982,
 0.18107616099071208,
 0.18103132351120466,
 0.17705074257425743,
 0.18107616099071208,
 0.18107930607187112,
 0.18065675340768278,
 0.1803283767038414,
 0.17825882352941178,
 0.1767356037151703,
 0.1784313482728736,
 0.17892910262766484,
 0.17812655086848636,
 0.1757695646781595,
 0.1751392843877677,
 0.17560594795539033,
 0.17464108910891088,
 0.17555514342235412,
 0.17442229102167184,
 0.17249102833807697,
 0.17115965346534653,
 0.1725949758693231,
 0.16999381417790424,
 0.171169409726519,
 0.16999381188118812,
 0.16999381188118812,
 0.1690050736295013,
 0.16989102167182663,
 0.17022153465346535,
 0.17124334365325078,
 0.1703059581320451,
 0.17113737623762376,
 0.16965977978473337,
 0.17320123839009285,
 0.173135750525925,
 0.17020047023883184,
 0.16975533775436027,
 0.16947536084903625,
 0.1690662075990327,
 0.1686464294569952,
 0.17217192331478046,
 0.1716821620102574,
 0.1682803414573797,
 0.16624211697786573,
 0.17221590206504267,
 0.17030303030303032,
 0.1680716934487021,
 0.1695190770736204,
 0.1714041435521406,
 0.1714383586119028,
 0.1637452119115285,
 0.16430021037000372,
 0.16413771788849055,
 0.16392013845963654,
 0.16385480855394896,
 0.16147357485211572,
 0.1610993745690808,
 0.16110442260442262,
 0.15896687116564417,
 0.16033269838785796,
 0.16478650306748466,
 0.16034596577017116,
 0.16324572127139364,
 0.16196456933414785,
 0.1624906484322264,
 0.16399633251833742,
 0.1626491917484431,
 0.1616576469354457,
 0.16263288876297746,
 0.1627720240816017,
 0.16190370165570125,
 0.160552893475857,
 0.15936397828218526,
 0.15941180345627684,
 0.16366257228793296,
 0.15760647399070318,
 0.1543055905729609,
 0.1588543008496929,
 0.15421948365427457,
 0.15421948365427457,
 0.15319198423288327,
 0.1533272036287851,
 0.15651342405296065,
 0.15225917290465088,
 0.15161476213830308,
 0.15187109422864845,
 0.152991526464448,
 0.1525496434690741,
 0.15354215384615386,
 0.1547088452088452,
 0.1532648718615016,
 0.15292716049382715,
 0.1527928454797099,
 0.15324830560690078,
 0.1490602873258887,
 0.15065925925925924,
 0.1490525663732042,
 0.15275463301236986,
 0.14890191540508935,
 0.15113370301910042,
 0.15208118081180813,
 0.15101383932136342,
 0.15226847290640394,
 0.1509476923076923,
 0.15423015384615382,
 0.15317784615384614,
 0.15157278784694211,
 0.1513349753694581,
 0.1515014164305949,
 0.1511013015549594,
 0.15114517916512746,
 0.15085947313178588,
 0.1540744369592538,
 0.1539228670259795,
 0.1537833079634428,
 0.15166968069346795,
 0.1527595887454671,
 0.15272202886827085,
 0.15253450619398615,
 0.1526366759582138,
 0.15164307316013012,
 0.15158723437160543,
 0.15348151165944102,
 0.1526929013198366,
 0.15274916811915704,
 0.15274916811915704,
 0.1526179433714727,
 0.152524536438543,
 0.1530985221674877,
 0.15710547616302925,
 0.15514215080346105,
 0.1542040014729348,
 0.15582019704433497,
 0.15553288260602335,
 0.15234215384615385,
 0.1560369685767098,
 0.15527999475593451,
 0.15138337012509198,
 0.15396837126810523,
 0.15049178317390235,
 0.15324118705367284,
 0.15324118705367284,
 0.15198920112897288,
 0.15225076828518747,
 0.15292549919036907,
 0.1536414197043251,
 0.1536414197043251,
 0.1526953552673087,
 0.1518276923076923,
 0.15176519226888607,
 0.14971113438875147,
 0.14867323542170166,
 0.14791245376078915,
 0.14732964329643297,
 0.1469002463054187,
 0.14683043960103437,
 0.1468485221674877,
 0.14440106786539791,
 0.1458128078817734,
 0.14541974396848845,
 0.14456527093596058,
 0.14444676923076924,
 0.14444676923076924,
 0.14418324662002371,
 0.14418324662002371,
 0.14418324662002371,
 0.14390565817663922,
 0.14416502463054187,
 0.14492808850645358,
 0.14415006150061502,
 0.1435276482549746,
 0.14499345569845823,
 0.1513280151316961,
 0.15127227634640292,
 0.14691378495059476,
 0.14719381958645764,
 0.14761476923076922,
 0.14730927246264666,
 0.14470536926356137,
 0.14496092143150965,
 0.14508308931410646,
 0.14483347733877935,
 0.14488664616291275,
 0.14461332498142315,
 0.14479991643984588,
 0.14458950866902823,
 0.14386453201970445,
 0.14312172400867657,
 0.14344320987654322,
 0.14335471930906848,
 0.14335471930906848,
 0.14397565603443396,
 0.1437824583603627,
 0.14420617283950615,
 0.14417766810610733,
 0.14244170265268352,
 0.14244170265268352,
 0.14469262529753585,
 0.14481727607507136,
 0.14634720414842856,
 0.1442955914095071,
 0.14433115461966167,
 0.14424245708367253,
 0.14421218716397724,
 0.14421218716397724,
 0.14424754339105664,
 0.1437366025311905,
 0.14415295136740502,
 0.1441432098765432,
 0.1443213844252163,
 0.14377277311421066,
 0.14359827914173917,
 0.14359827914173917,
 0.143679591172963,
 0.14189313206543094,
 0.1417279348313831,
 0.1416930001429649,
 0.1418061728395062,
 0.14189864029666255,
 0.1415159001365898,
 0.14189864029666255,
 0.14356809225290632,
 0.14377997527812114,
 0.1430101246105919,
 0.1429574506613188,
 0.14344993819530283,
 0.14322173940408914,
 0.14297488690235657,
 0.1412530864197531,
 0.14106360838774584,
 0.14326134322554362,
 0.14224540180224662,
 0.1414102088740576,
 0.14134487021013598,
 0.14108765432098766,
 0.14108765432098766,
 0.1420098704503393,
 0.1418719369693623,
 0.1418719369693623,
 0.14190692008758607,
 0.14195942712521645,
 0.14104621863242553,
 0.1412530864197531,
 0.13797596265957957,
 0.13805925925925924,
 0.13789106620566519,
 0.13783220234423196,
 0.13774926386087094,
 0.13778324296856886,
 0.13827535681337166,
 0.1383434375343199,
 0.1383434375343199,
 0.13874569279600837,
 0.13961516135805063,
 0.13973279479168338,
 0.14097617606738383,
 0.14168114395923392,
 0.14235407568197617,
 0.1417849196538937,
 0.1420955563807402,
 0.14216594427244583,
 0.14161263606393074,
 0.1420775968724933,
 0.14121875034709838,
 0.14111443257268574,
 0.14107963624169018,
 0.14095047545976325,
 0.14093326492251984,
 0.14094636508429612,
 0.13995049504950494,
 0.13993317658705606,
 0.1384583127775037,
 0.13849435410547142,
 0.13847727056861509,
 0.13885219542362398,
 0.1395208273456282,
 0.14042164285096767,
 0.13963856912984282,
 0.13921290448444168,
 0.13928152293419313,
 0.1397847866419295,
 0.13747409555054438,
 0.13885891089108912,
 0.13747409555054438,
 0.13956228103864093,
 0.13956228103864093,
 0.13995789473684211,
 0.13895373887793538,
 0.13932921824413808,
 0.13952970297029704,
 0.1372487774525333,
 0.13733168622606548,
 0.13822453773131949,
 0.13605011800467076,
 0.13615105912030567,
 0.1381211372064277,
 0.138545229244114,
 0.13761957730812013,
 0.1377402766730456,
 0.1377743627434604,
 0.1377402766730456,
 0.1368108227769045,
 0.13661271776357276,
 0.13661271776357276,
 0.13538666897378537,
 0.13542014365364885,
 0.13727554715209037,
 0.13565115127506808,
 0.1354516125044809,
 0.13548418984542007,
 0.13550093303179725,
 0.13542600896860987,
 0.13547621695769843,
 0.13478998884896545,
 0.13348044851586743,
 0.13348044851586743,
 0.13357273893450075,
 0.13357273893450075,
 0.13144801980198018,
 0.13112345679012344,
 0.13128553770086526,
 0.12521878862793573,
 0.12520485978074133,
 0.1252667894990664,
 0.1250063397539062,
 0.12409838091706835,
 0.12417649961476199,
 0.12411372064276885,
 0.1242687109138592,
 0.12429947845420412,
 0.12428563117587862,
 0.12429947845420412,
 0.1243455043517459,
 0.12314161192537112,
 0.12309590183508602,
 0.12277263228183853,
 0.12278622426824003,
 0.12278622426824003,
 0.12307120743034056,
 0.1233293469751704,
 0.12321883840864137,
 0.12303205918618988,
 0.12318856704867165,
 0.12314289598240216,
 0.12324936208318955,
 0.12541306738837604,
 0.12550597273528893,
 0.12534938032102214,
 0.12521109174300585,
 0.12121084701660048,
 0.12112112112112113,
 0.12518014065184344,
 0.1213004733713184,
 0.12125551341133446,
 0.12125551341133446,
 0.11914444444444446,
 0.12529806397410395,
 0.12529806397410395,
 0.11874568753080335,
 0.11904050198248496,
 0.12302142374772991,
 0.12261913557443664,
 0.12290835842007235,
 0.12179815384615385,
 0.12214557344027134,
 0.12187315270935961,
 0.1232423081675522,
 0.12336594747562586,
 0.12311942484356278,
 0.12169041769041769,
 0.12191912838949726,
 0.12169041769041769,
 0.12191912838949726,
 0.12269410319410319,
 0.12269410319410319,
 0.12296798643662113,
 0.12296798643662113,
 0.12207851676602408,
 0.12189860690818181,
 0.12260093549975382,
 0.122392278058701,
 0.1209595588235294,
 0.1223411774974154,
 0.12215887122016485,
 0.12294727159592024,
 0.1219413516710814,
 0.12185895969679755,
 0.12281150002763838,
 0.12290193070317129,
 0.12275935789454284,
 0.12187184848112163,
 0.12164967437406778,
 0.12258577902460077,
 0.12044708830434926,
 0.12141149717649106,
 0.12041773909551086,
 0.120062263459895,
 0.12211478878145544,
 0.12206719609040928,
 0.12446051986267778,
 0.12392870223415944,
 0.12395283479960899,
 0.124259079378184,
 0.12428952820629686,
 0.12573105134474327,
 0.12601095587631694,
 0.12591854374851552,
 0.12557753357753357,
 0.12591854374851552,
 0.1241518544727969,
 0.1241518544727969,
 0.12389126450824679,
 0.1241518544727969,
 0.1241518544727969,
 0.12298752910813411,
 0.12631767105543462,
 0.12607280767695664,
 0.12607280767695664,
 0.122660158633313,
 0.12306833402303186,
 0.12350243902439025,
 0.12407362113244466,
 0.1242130703174164,
 0.1242130703174164,
 0.1242130703174164,
 0.1242130703174164,
 0.1242130703174164,
 0.12821903518931613,
 0.13467069022624575,
 0.13475303938822106,
 0.13976576854291592,
 0.14913833870382387,
 0.14803246977800752,
 0.14965644746022844,
 0.14935731707317074,
 0.1346609756097561,
 0.1346609756097561,
 0.13655243902439024,
 0.13493067240496553,
 0.13528029540114134,
 0.13067073170731708,
 0.12566760151201073,
 0.12605463427521643,
 0.12876231676254188,
 0.12472877338297565,
 0.12922251223730463,
 0.12914069184696247,
 0.12496255109864375,
 0.12906312906312906,
 0.1290916870415648,
 0.1292274783033859,
 0.12928615083730596,
 0.1295334570013243,
 0.12892555922258891,
 0.12888129123232334,
 0.12637507635919365,
 0.12612924072266518,
 0.12777180683455874,
 0.1277406041661579,
 0.12487609560780293,
 0.1282792287039297,
 0.12826357535082367,
 0.12851448832375595,
 0.12792337725719863,
 0.12801709401709402,
 0.12786035046614927,
 0.12817948717948718,
 0.1281638383591747,
 0.12810441079963905,
 0.1283982419728971,
 0.12976277639478695,
 0.12983882783882786,
 0.13054138494959605,
 0.1305095292710901,
 0.13050953245588062,
 0.13171964639250333,
 0.1357903088001953,
 0.13783760683760685,
 0.13783760683760685,
 0.13574391761634008,
 0.1355141099502002,
 0.13556043956043956,
 0.13649588713417465,
 0.13531623931623932,
 0.13700407724797967,
 0.13497400473528767,
 0.13009038719921825,
 0.12998242573653251,
 0.13009594960814472,
 0.1350392932103285,
 0.13499003999858494,
 0.12887416943977345,
 0.13278354890199603,
 0.12954727532347493,
 0.13235531135531137,
 0.13143141470696199,
 0.13188584443152043,
 0.1318376216819687,
 0.1273603249626042,
 0.1273603249626042,
 0.13366915403173799,
 0.1338778998778999,
 0.13366915403173799,
 0.1337180586332089,
 0.13376683583837598,
 0.1266036334182749,
 0.12755151810754786,
 0.1265171858216971,
 0.1265540787708816,
 0.12656043956043955,
 0.12564346764346765,
 0.12619221945624054,
 0.12625076303259675,
 0.12523867659626417,
 0.12522965626941776,
 0.125006105006105,
 0.12499084360883897,
 0.12300854700854702,
 0.12594644731382265,
 0.126004884004884,
 0.12664468864468864,
 0.126629227200586,
 0.1270772799413991,
 0.13709756157094388,
 0.12677707162063065,
 0.1231427873457921,
 0.12414601391771457,
 0.12422962651339617,
 0.1241914997557401,
 0.1241914997557401,
 0.1229904831625183,
 0.12530352998656405,
 0.12326007326007327,
 0.12610243902439025,
 0.12627182806203444,
 0.12626421941387755,
 0.12429816727610016,
 0.12518426624650425,
 0.12434065934065934,
 0.12395615103532277,
 0.123311767578125,
 0.1230743956498549,
 0.12521176614182838,
 0.12373673750697929,
 0.12368856447688564,
 0.12272594574869236,
 0.12257853244390539,
 0.12390359397765906,
 0.12294947655894402,
 0.12307729644460623,
 0.12300094044838152,
 0.12384823026295837,
 0.12288565967903406,
 0.12381818733133207,
 0.12386325719659053,
 0.1236154009526988,
 0.12293041182361689,
 0.12306112528861343,
 0.12400412922030604,
 0.12481945244519904,
 0.12378254133358549,
 0.1238274262498863,
 0.12280576254828596,
 0.12292230757483572,
 0.12295211147399482,
 0.12396992845883352,
 0.1247994303519248,
 0.12449230724598441,
 0.1246684125226812,
 0.1246986214734169,
 0.12463836914018744,
 0.12346432889963724,
 0.12370755560509539,
 0.12334274579582048,
 0.12447730792845009,
 0.12418577998288144,
 0.12441704098294185,
 0.12315458937198068,
 0.12332016288596166,
 0.12430585219991458,
 0.1243100641983675,
 0.1243100641983675,
 0.12327123300265039,
 0.12427577479545063,
 0.12418577998288144,
 0.12317780732503324,
 0.12455690072639224,
 0.1244255459127894,
 0.12347452499092339,
 0.12319010429252168,
 0.12329964035036836,
 0.12400965850959875,
 0.12403947457446914,
 0.12346278786472534,
 0.1230381257314568,
 0.12306785330725528,
 0.1230232673285262,
 0.12311194300205289,
 0.12295307355548318,

In [14]:
dfcorrlaos = pd.DataFrame({'ylaos': ylaoslist, 'xlaos': xlaosreshape})
dfcorrlaos
dfcorrlaos = dfcorrlaos.corr()
dfcorrlaos

          ylaos     xlaos
ylaos  1.000000  0.998479
xlaos  0.998479  1.000000

In [15]:
from sklearn.model_selection import train_test_split
# xtr, xts, ytr, yts = train_test_split(df[['JCI']][:-forecast_out], df['prediction'][:-forecast_out], random_state=10)
xtrlaos, xtslaos, ytrlaos, ytslaos = train_test_split(xlaos, ylaos, random_state=5)
xtrlaos

array([[0.15410231],
       [0.12191913],
       [0.15324831],
       ...,
       [0.11932048],
       [0.17579301],
       [0.12373674]])

In [16]:
def evaluate(model, test_features, test_labels):
    predictions = model.predict(test_features)
    errors = abs(predictions - test_labels)
    mape = 100 * np.mean(errors / test_labels)
    accuracy = 100 - mape
    rmse = np.sqrt(mean_squared_error(test_labels, predictions))
    r2 = r2_score(test_labels, predictions)
    print('Model Performance')
    print('Average Error: {:0.4f} degrees.'.format(np.mean(errors)))
    print('Accuracy = {:0.4f}%.'.format(accuracy))
    print('RMSE = {:0.4f}'.format(rmse))
    print('R2 Score = {:0.4f}.'.format(r2))
    vals = [accuracy,rmse,r2]
    return vals

In [17]:
lnr_grid = {
    'fit_intercept': [True, False],
    'normalize': [True, False],
    'copy_X': [True, False],
    'n_jobs':['int', None]
}
print(lnr_grid)

{'fit_intercept': [True, False], 'normalize': [True, False], 'copy_X': [True, False], 'n_jobs': ['int', None]}

In [18]:
lnr = LinearRegression()
lnr_random = RandomizedSearchCV(estimator=lnr, param_distributions=lnr_grid, n_iter=100,
                               cv=5, verbose=2, random_state=41, n_jobs=-1)

lnr_random.fit(xtrlaos, ytrlaos)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

//anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:281: UserWarning: The total space of parameters 16 is smaller than n_iter=100. Running 16 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  80 out of  80 | elapsed:    1.1s finished

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=LinearRegression(copy_X=True, fit_intercept=True,
                                              n_jobs=None, normalize=False),
                   iid='deprecated', n_iter=100, n_jobs=-1,
                   param_distributions={'copy_X': [True, False],
                                        'fit_intercept': [True, False],
                                        'n_jobs': ['int', None],
                                        'normalize': [True, False]},
                   pre_dispatch='2*n_jobs', random_state=41, refit=True,
                   return_train_score=False, scoring=None, verbose=2)

In [19]:
lnr_random.best_params_

{'normalize': True, 'n_jobs': 'int', 'fit_intercept': False, 'copy_X': True}

In [20]:
## LinearRegression with default hyperparameters

base_lnr = LinearRegression()
base_lnr.fit(xtrlaos, ytrlaos)
base_lnr_accuracy = evaluate(base_lnr, xtslaos, ytslaos)
base_lnr_accuracy

Model Performance
Average Error: 0.0010 degrees.
Accuracy = 99.2495%.
RMSE = 0.0017
R2 Score = 0.9968.

[99.24951646919729, 0.001691381809153203, 0.9968264739087696]

In [21]:
## LinearRegression with default best hyperparameters

best_lnr = lnr_random.best_estimator_
best_lnr.fit(xtrlaos, ytrlaos)
best_lnr_accuracy = evaluate(best_lnr, xtrlaos, ytrlaos)

Model Performance
Average Error: 0.0009 degrees.
Accuracy = 99.3118%.
RMSE = 0.0016
R2 Score = 0.9970.

## Ridge

In [22]:
rdg_grid = {
    'alpha': np.arange(1,2,0.01),
    'fit_intercept': [True, False],
    'max_iter': [10,100,1000,10000,100000],
    'solver': ['auto', 'svd', 'cholesky', 'lsqr', 'sparse_cg', 'sag', 'saga']
}
print(rdg_grid)

{'alpha': array([1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09, 1.1 ,
       1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.2 , 1.21,
       1.22, 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.3 , 1.31, 1.32,
       1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.4 , 1.41, 1.42, 1.43,
       1.44, 1.45, 1.46, 1.47, 1.48, 1.49, 1.5 , 1.51, 1.52, 1.53, 1.54,
       1.55, 1.56, 1.57, 1.58, 1.59, 1.6 , 1.61, 1.62, 1.63, 1.64, 1.65,
       1.66, 1.67, 1.68, 1.69, 1.7 , 1.71, 1.72, 1.73, 1.74, 1.75, 1.76,
       1.77, 1.78, 1.79, 1.8 , 1.81, 1.82, 1.83, 1.84, 1.85, 1.86, 1.87,
       1.88, 1.89, 1.9 , 1.91, 1.92, 1.93, 1.94, 1.95, 1.96, 1.97, 1.98,
       1.99]), 'fit_intercept': [True, False], 'max_iter': [10, 100, 1000, 10000, 100000], 'solver': ['auto', 'svd', 'cholesky', 'lsqr', 'sparse_cg', 'sag', 'saga']}

In [23]:
rdg = Ridge()
rdg_random = RandomizedSearchCV(estimator=rdg, param_distributions=rdg_grid, n_iter=100,
                               cv=5, verbose=2, random_state=41, n_jobs=-1)

rdg_random.fit(xtrlaos, ytrlaos)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.

Fitting 5 folds for each of 100 candidates, totalling 500 fits

[Parallel(n_jobs=-1)]: Done 500 out of 500 | elapsed:    0.5s finished

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=Ridge(alpha=1.0, copy_X=True, fit_intercept=True,
                                   max_iter=None, normalize=False,
                                   random_state=None, solver='auto',
                                   tol=0.001),
                   iid='deprecated', n_iter=100, n_jobs=-1,
                   param_distributions={'alpha': array([1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09, 1.1 ,
       1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.2 , 1.21,...
       1.66, 1.67, 1.68, 1.69, 1.7 , 1.71, 1.72, 1.73, 1.74, 1.75, 1.76,
       1.77, 1.78, 1.79, 1.8 , 1.81, 1.82, 1.83, 1.84, 1.85, 1.86, 1.87,
       1.88, 1.89, 1.9 , 1.91, 1.92, 1.93, 1.94, 1.95, 1.96, 1.97, 1.98,
       1.99]),
                                        'fit_intercept': [True, False],
                                        'max_iter': [10, 100, 1000, 10000,
                                                     100000],
                                        'solver': ['auto', 'svd', 'cholesky',
                                                   'lsqr', 'sparse_cg', 'sag',
                                                   'saga']},
                   pre_dispatch='2*n_jobs', random_state=41, refit=True,
                   return_train_score=False, scoring=None, verbose=2)

In [24]:
rdg_random.best_params_

{'solver': 'auto', 'max_iter': 10000, 'fit_intercept': False, 'alpha': 1.0}

In [25]:
## Ridge with default hyperparameter
base_rdg = Ridge()
base_rdg.fit(xtrlaos, ytrlaos)
base_rdg_accuracy = evaluate(base_rdg, xtslaos, ytslaos)

Model Performance
Average Error: 0.0125 degrees.
Accuracy = 89.2886%.
RMSE = 0.0146
R2 Score = 0.7621.

In [26]:
## Ridge with best hyperparameters

best_rdg = rdg_random.best_estimator_
best_rdg.fit(xtrlaos, ytrlaos)
best_rdg_accuracy = evaluate(best_rdg, xtslaos, ytslaos)

Model Performance
Average Error: 0.0059 degrees.
Accuracy = 95.4293%.
RMSE = 0.0063
R2 Score = 0.9566.

## Lasso

In [27]:
las_grid = {
    'alpha': np.arange(1,2,0.01),
    'fit_intercept': [True, False],
    'max_iter': [10,100,1000,10000,100000],
    'precompute': [True, False],
    'warm_start': [True, False],
    'random_state': np.arange(20,30,1),
    'selection': ['random', 'cyclic']
}
print(las_grid)

{'alpha': array([1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09, 1.1 ,
       1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.2 , 1.21,
       1.22, 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.3 , 1.31, 1.32,
       1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.4 , 1.41, 1.42, 1.43,
       1.44, 1.45, 1.46, 1.47, 1.48, 1.49, 1.5 , 1.51, 1.52, 1.53, 1.54,
       1.55, 1.56, 1.57, 1.58, 1.59, 1.6 , 1.61, 1.62, 1.63, 1.64, 1.65,
       1.66, 1.67, 1.68, 1.69, 1.7 , 1.71, 1.72, 1.73, 1.74, 1.75, 1.76,
       1.77, 1.78, 1.79, 1.8 , 1.81, 1.82, 1.83, 1.84, 1.85, 1.86, 1.87,
       1.88, 1.89, 1.9 , 1.91, 1.92, 1.93, 1.94, 1.95, 1.96, 1.97, 1.98,
       1.99]), 'fit_intercept': [True, False], 'max_iter': [10, 100, 1000, 10000, 100000], 'precompute': [True, False], 'warm_start': [True, False], 'random_state': array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]), 'selection': ['random', 'cyclic']}

In [28]:
las = Lasso()
las_random = RandomizedSearchCV(estimator=las, param_distributions=las_grid, n_iter=100,
                               cv=5, verbose=2, random_state=41, n_jobs=-1)

las_random.fit(xtrlaos, ytrlaos)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.

Fitting 5 folds for each of 100 candidates, totalling 500 fits

[Parallel(n_jobs=-1)]: Done 500 out of 500 | elapsed:    0.4s finished

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=Lasso(alpha=1.0, copy_X=True, fit_intercept=True,
                                   max_iter=1000, normalize=False,
                                   positive=False, precompute=False,
                                   random_state=None, selection='cyclic',
                                   tol=0.0001, warm_start=False),
                   iid='deprecated', n_iter=100, n_jobs=-1,
                   param_distributions={'alpha': array([1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09, 1.1...
       1.88, 1.89, 1.9 , 1.91, 1.92, 1.93, 1.94, 1.95, 1.96, 1.97, 1.98,
       1.99]),
                                        'fit_intercept': [True, False],
                                        'max_iter': [10, 100, 1000, 10000,
                                                     100000],
                                        'precompute': [True, False],
                                        'random_state': array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
                                        'selection': ['random', 'cyclic'],
                                        'warm_start': [True, False]},
                   pre_dispatch='2*n_jobs', random_state=41, refit=True,
                   return_train_score=False, scoring=None, verbose=2)

In [29]:
las_random.best_params_

{'warm_start': True,
 'selection': 'random',
 'random_state': 28,
 'precompute': True,
 'max_iter': 100000,
 'fit_intercept': True,
 'alpha': 1.4300000000000004}

In [30]:
## lasso with default hyperparameters

base_las = Lasso()
base_las.fit(xtrlaos, ytrlaos)
base_las_accuracy = evaluate(base_rdg, xtslaos, ytslaos)

Model Performance
Average Error: 0.0125 degrees.
Accuracy = 89.2886%.
RMSE = 0.0146
R2 Score = 0.7621.

In [31]:
## Lasso with best hyperparameters

best_las = las_random.best_estimator_
best_las.fit(xtrlaos, ytrlaos)
best_las_accuracy = evaluate(best_las, xtslaos, ytslaos)

Model Performance
Average Error: 0.0256 degrees.
Accuracy = 77.9255%.
RMSE = 0.0301
R2 Score = -0.0052.

## ElasticNet

In [32]:
elas_grid = {
    'alpha': np.arange(1,2,0.01),
    'l1_ratio': np.arange(0.1,1,0.01),
    'fit_intercept': [True, False],
    'precompute': [True, False],
    'max_iter': [10,100,1000,10000,100000],
    'warm_start': [True, False],
    'positive': [True, False],
    'random_state': np.arange(20,30,1),
    'selection': ['random', 'cyclic']
}
print(elas_grid)

{'alpha': array([1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09, 1.1 ,
       1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.2 , 1.21,
       1.22, 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.3 , 1.31, 1.32,
       1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.4 , 1.41, 1.42, 1.43,
       1.44, 1.45, 1.46, 1.47, 1.48, 1.49, 1.5 , 1.51, 1.52, 1.53, 1.54,
       1.55, 1.56, 1.57, 1.58, 1.59, 1.6 , 1.61, 1.62, 1.63, 1.64, 1.65,
       1.66, 1.67, 1.68, 1.69, 1.7 , 1.71, 1.72, 1.73, 1.74, 1.75, 1.76,
       1.77, 1.78, 1.79, 1.8 , 1.81, 1.82, 1.83, 1.84, 1.85, 1.86, 1.87,
       1.88, 1.89, 1.9 , 1.91, 1.92, 1.93, 1.94, 1.95, 1.96, 1.97, 1.98,
       1.99]), 'l1_ratio': array([0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ,
       0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31,
       0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42,
       0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53,
       0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64,
       0.65, 0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75,
       0.76, 0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86,
       0.87, 0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97,
       0.98, 0.99]), 'fit_intercept': [True, False], 'precompute': [True, False], 'max_iter': [10, 100, 1000, 10000, 100000], 'warm_start': [True, False], 'positive': [True, False], 'random_state': array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]), 'selection': ['random', 'cyclic']}

In [33]:
elas = ElasticNet()
elas_random = RandomizedSearchCV(estimator=elas, param_distributions=elas_grid, n_iter=100,
                               cv=5, verbose=2, random_state=41, n_jobs=-1)

elas_random.fit(xtrlaos, ytrlaos)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.

Fitting 5 folds for each of 100 candidates, totalling 500 fits

[Parallel(n_jobs=-1)]: Done 500 out of 500 | elapsed:    0.5s finished

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=ElasticNet(alpha=1.0, copy_X=True,
                                        fit_intercept=True, l1_ratio=0.5,
                                        max_iter=1000, normalize=False,
                                        positive=False, precompute=False,
                                        random_state=None, selection='cyclic',
                                        tol=0.0001, warm_start=False),
                   iid='deprecated', n_iter=100, n_jobs=-1,
                   param_distributions={'alpha': array([1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06,...
       0.87, 0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97,
       0.98, 0.99]),
                                        'max_iter': [10, 100, 1000, 10000,
                                                     100000],
                                        'positive': [True, False],
                                        'precompute': [True, False],
                                        'random_state': array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
                                        'selection': ['random', 'cyclic'],
                                        'warm_start': [True, False]},
                   pre_dispatch='2*n_jobs', random_state=41, refit=True,
                   return_train_score=False, scoring=None, verbose=2)

In [34]:
elas_random.best_params_

{'warm_start': False,
 'selection': 'cyclic',
 'random_state': 24,
 'precompute': True,
 'positive': False,
 'max_iter': 1000,
 'l1_ratio': 0.8199999999999996,
 'fit_intercept': True,
 'alpha': 1.2600000000000002}

In [35]:
## elasticnet with default hyperparameters
base_elas = ElasticNet()
base_elas.fit(xtrlaos, ytrlaos)
base_elas_accuracy = evaluate(base_elas, xtslaos, ytslaos)

Model Performance
Average Error: 0.0256 degrees.
Accuracy = 77.9255%.
RMSE = 0.0301
R2 Score = -0.0052.

In [36]:
## elasticnet with best hyperparameters

best_elas = elas_random.best_estimator_
best_elas.fit(xtrlaos, ytrlaos)
best_elas_accuracy = evaluate(best_elas, xtslaos, ytslaos)

Model Performance
Average Error: 0.0256 degrees.
Accuracy = 77.9255%.
RMSE = 0.0301
R2 Score = -0.0052.

In [37]:
## LinearRegression with default best hyperparameters
print('best linear:')
best_lnr = lnr_random.best_estimator_
best_lnr.fit(xtrlaos, ytrlaos)
best_lnr_accuracy = evaluate(best_lnr, xtslaos, ytslaos)

## Ridge with best hyperparameters
print('best ridge:')
best_rdg = rdg_random.best_estimator_
best_rdg.fit(xtrlaos, ytrlaos)
best_rdg_accuracy = evaluate(best_rdg, xtslaos, ytslaos)

## lasso with default hyperparameters
print('base lasso:')
base_las = Lasso()
base_las.fit(xtrlaos, ytrlaos)
base_las_accuracy = evaluate(base_rdg, xtslaos, ytslaos)

## elasticnet with best hyperparameters
print('best elastic:')
best_elas = elas_random.best_estimator_
best_elas.fit(xtrlaos, ytrlaos)
best_elas_accuracy = evaluate(best_elas, xtslaos, ytslaos)

best linear:
Model Performance
Average Error: 0.0010 degrees.
Accuracy = 99.2496%.
RMSE = 0.0017
R2 Score = 0.9968.
best ridge:
Model Performance
Average Error: 0.0059 degrees.
Accuracy = 95.4293%.
RMSE = 0.0063
R2 Score = 0.9566.
base lasso:
Model Performance
Average Error: 0.0125 degrees.
Accuracy = 89.2886%.
RMSE = 0.0146
R2 Score = 0.7621.
best elastic:
Model Performance
Average Error: 0.0256 degrees.
Accuracy = 77.9255%.
RMSE = 0.0301
R2 Score = -0.0052.

In [38]:
#create and train the linear regression model
lr = best_lnr
# {'normalize': True, 'n_jobs': 'int', 'fit_intercept': True, 'copy_X': True}
lr.fit(xtrlaos, ytrlaos)

import joblib
joblib.dump(lr,'regressionlaosi')

im = joblib.load('regressionlaosi')
im

LinearRegression(copy_X=True, fit_intercept=False, n_jobs='int', normalize=True)

In [39]:
lrconfidence = lr.score(xtslaos, ytslaos)
lrconfidence
xtslaos.shape

(402, 1)

In [40]:
ylr = im.predict(xtslaos)
dflaosbaru = pd.DataFrame({ 'ylaos':ytslaos ,'predictlaos': ylr})
dflaosbaru

        ylaos  predictlaos
0    0.125073     0.123832
1    0.098417     0.096881
2    0.178797     0.176399
3    0.164787     0.160215
4    0.095203     0.095958
5    0.097489     0.097272
6    0.093351     0.093991
7    0.111182     0.111045
8    0.180811     0.182504
9    0.174516     0.174280
10   0.090087     0.091728
11   0.102533     0.102711
12   0.121596     0.123346
13   0.168646     0.168942
14   0.143355     0.143249
15   0.153327     0.153079
16   0.171160     0.172364
17   0.093319     0.092810
18   0.076929     0.077209
19   0.109686     0.109605
20   0.128881     0.128831
21   0.170212     0.172382
22   0.173938     0.172809
23   0.161038     0.160940
24   0.182312     0.179162
25   0.122806     0.123736
26   0.077370     0.078228
27   0.121941     0.122857
28   0.116427     0.114850
29   0.124212     0.125736
..        ...          ...
372  0.162184     0.162027
373  0.124212     0.124120
374  0.172361     0.171950
375  0.088499     0.088325
376  0.097727     0.096862
377  0.155573     0.155731
378  0.177393     0.177555
379  0.166242     0.168157
380  0.128398     0.128010
381  0.123074     0.123221
382  0.159364     0.160435
383  0.124152     0.125826
384  0.095618     0.095651
385  0.139639     0.140319
386  0.097934     0.098489
387  0.087609     0.087477
388  0.094164     0.094421
389  0.120134     0.120046
390  0.161658     0.162530
391  0.122902     0.122721
392  0.120273     0.120345
393  0.143976     0.143249
394  0.178689     0.178392
395  0.126645     0.125912
396  0.111127     0.111144
397  0.088672     0.089264
398  0.087591     0.087656
399  0.161187     0.159306
400  0.157450     0.156348
401  0.103537     0.103461

[402 rows x 2 columns]

In [41]:
from sklearn.metrics import r2_score
print('R2', r2_score(dflaosbaru['ylaos'], dflaosbaru['predictlaos']))
from sklearn.metrics import r2_score
print('R2 sqrt', np.sqrt(r2_score(dflaosbaru['ylaos'], dflaosbaru['predictlaos']))) ## hasilnya sama dengan korelasi untuk single regression

R2 0.9968419473539565
R2 sqrt 0.9984197250425076

In [42]:
dfkurslaos = df2[['Laos']]
dfkurslaos

dfkurslaos['predictkurslaos'] = dfkurslaos[['Laos']].shift(-forecast_out)

dfkurslaos

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

         Laos  predictkurslaos
0     8000.00          8021.00
1     8021.00          8021.00
2     8021.00          8003.00
3     8003.00          8018.00
4     8018.00          8015.00
5     8015.00          8013.00
6     8013.00          8009.00
7     8009.00          7991.00
8     7991.00          8005.00
9     8005.00          8000.00
10    8000.00          8015.00
11    8015.00          8018.00
12    8018.00          8015.00
13    8015.00          8010.00
14    8010.00          7995.00
15    7995.00          7991.00
16    7991.00          7991.00
17    7991.00          8011.00
18    8011.00          8009.00
19    8009.00          8020.00
20    8020.00          8010.00
21    8010.00          8007.00
22    8007.00          8006.00
23    8006.00          7990.00
24    7990.00          8011.00
25    8011.00          8010.00
26    8010.00          8011.00
27    8011.00          8001.00
28    8001.00          8001.00
29    8001.00          7998.00
...       ...              ...
1578  8823.45          8824.45
1579  8824.45          8840.00
1580  8840.00          8823.45
1581  8823.45          8813.48
1582  8813.48          8813.48
1583  8813.48          8860.00
1584  8860.00          8857.00
1585  8857.00          8860.00
1586  8860.00          8831.43
1587  8831.43          8858.00
1588  8858.00          8832.42
1589  8832.42          8833.42
1590  8833.42          8855.00
1591  8855.00          8871.00
1592  8871.00          8837.41
1593  8837.41          8843.39
1594  8843.39          8839.40
1595  8839.40          8838.41
1596  8838.41          8833.42
1597  8833.42          8860.00
1598  8860.00          8855.00
1599  8855.00          8838.41
1600  8838.41          8865.00
1601  8865.00          8853.36
1602  8853.36          8875.00
1603  8875.00          8875.00
1604  8875.00          8843.39
1605  8843.39          8875.00
1606  8875.00          8870.00
1607  8870.00              NaN

[1608 rows x 2 columns]

In [43]:
xkurslaos = np.array(dfkurslaos.drop(['predictkurslaos'], axis=1))

xkurslaos
#remove the 'n' rows
xkurslaos = xkurslaos[:-forecast_out]
xkurslaos

array([[8000.  ],
       [8021.  ],
       [8021.  ],
       ...,
       [8875.  ],
       [8843.39],
       [8875.  ]])

In [44]:
ykurslaos = np.array(dfkurslaos['predictkurslaos'])

ykurslaos
#remove the 'n' rows
ykurslaos = ykurslaos[:-forecast_out]
ykurslaos

array([8021.  , 8021.  , 8003.  , ..., 8843.39, 8875.  , 8870.  ])

In [45]:
from sklearn.model_selection import train_test_split
# xtr, xts, ytr, yts = train_test_split(df[['JCI']][:-forecast_out], df['prediction'][:-forecast_out], random_state=10)
xtrklaos, xtsklaos, ytrklaos, ytsklaos = train_test_split(xkurslaos, ykurslaos, random_state=5)
xtrklaos

array([[8015.    ],
       [8124.73  ],
       [8115.    ],
       ...,
       [8300.    ],
       [8039.    ],
       [8216.7998]])

In [46]:
lnr_random.fit(xtrklaos, ytrklaos)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

//anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:281: UserWarning: The total space of parameters 16 is smaller than n_iter=100. Running 16 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  80 out of  80 | elapsed:    0.1s finished

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=LinearRegression(copy_X=True, fit_intercept=True,
                                              n_jobs=None, normalize=False),
                   iid='deprecated', n_iter=100, n_jobs=-1,
                   param_distributions={'copy_X': [True, False],
                                        'fit_intercept': [True, False],
                                        'n_jobs': ['int', None],
                                        'normalize': [True, False]},
                   pre_dispatch='2*n_jobs', random_state=41, refit=True,
                   return_train_score=False, scoring=None, verbose=2)

In [47]:
lnr_random.best_params_

{'normalize': True, 'n_jobs': 'int', 'fit_intercept': True, 'copy_X': True}

In [48]:
## LinearRegression with default hyperparameters

base_lnr = LinearRegression()
base_lnr.fit(xtrklaos, ytrklaos)
base_lnr_accuracy = evaluate(base_lnr, xtsklaos, ytsklaos)

Model Performance
Average Error: 7.2924 degrees.
Accuracy = 99.9119%.
RMSE = 11.8251
R2 Score = 0.9978.

In [49]:
## LinearRegression with default best hyperparameters

best_lnr = lnr_random.best_estimator_
best_lnr.fit(xtrklaos, ytrklaos)
best_lnr_accuracy = evaluate(best_lnr, xtsklaos, ytsklaos)

Model Performance
Average Error: 7.2924 degrees.
Accuracy = 99.9119%.
RMSE = 11.8251
R2 Score = 0.9978.

## Ridge

In [50]:
rdg_random.fit(xtrklaos, ytrklaos)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.

Fitting 5 folds for each of 100 candidates, totalling 500 fits

[Parallel(n_jobs=-1)]: Done 500 out of 500 | elapsed:    0.4s finished

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=Ridge(alpha=1.0, copy_X=True, fit_intercept=True,
                                   max_iter=None, normalize=False,
                                   random_state=None, solver='auto',
                                   tol=0.001),
                   iid='deprecated', n_iter=100, n_jobs=-1,
                   param_distributions={'alpha': array([1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09, 1.1 ,
       1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.2 , 1.21,...
       1.66, 1.67, 1.68, 1.69, 1.7 , 1.71, 1.72, 1.73, 1.74, 1.75, 1.76,
       1.77, 1.78, 1.79, 1.8 , 1.81, 1.82, 1.83, 1.84, 1.85, 1.86, 1.87,
       1.88, 1.89, 1.9 , 1.91, 1.92, 1.93, 1.94, 1.95, 1.96, 1.97, 1.98,
       1.99]),
                                        'fit_intercept': [True, False],
                                        'max_iter': [10, 100, 1000, 10000,
                                                     100000],
                                        'solver': ['auto', 'svd', 'cholesky',
                                                   'lsqr', 'sparse_cg', 'sag',
                                                   'saga']},
                   pre_dispatch='2*n_jobs', random_state=41, refit=True,
                   return_train_score=False, scoring=None, verbose=2)

In [51]:
rdg_random.best_params_

{'solver': 'saga',
 'max_iter': 10,
 'fit_intercept': True,
 'alpha': 1.3800000000000003}

In [52]:
## Ridge with default hyperparameter
base_rdg = Ridge()
base_rdg.fit(xtrklaos, ytrklaos)
base_rdg_accuracy = evaluate(base_rdg, xtsklaos, ytsklaos)

Model Performance
Average Error: 7.2924 degrees.
Accuracy = 99.9119%.
RMSE = 11.8251
R2 Score = 0.9978.

In [53]:
## Ridge with best hyperparameters

best_rdg = rdg_random.best_estimator_
best_rdg.fit(xtrklaos, ytrklaos)
best_rdg_accuracy = evaluate(best_rdg, xtsklaos, ytsklaos)

Model Performance
Average Error: 7.2863 degrees.
Accuracy = 99.9120%.
RMSE = 11.8222
R2 Score = 0.9978.

## Lasso

In [54]:
las_random.fit(xtrklaos, ytrklaos)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.

Fitting 5 folds for each of 100 candidates, totalling 500 fits

[Parallel(n_jobs=-1)]: Done 500 out of 500 | elapsed:    0.5s finished

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=Lasso(alpha=1.0, copy_X=True, fit_intercept=True,
                                   max_iter=1000, normalize=False,
                                   positive=False, precompute=False,
                                   random_state=None, selection='cyclic',
                                   tol=0.0001, warm_start=False),
                   iid='deprecated', n_iter=100, n_jobs=-1,
                   param_distributions={'alpha': array([1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09, 1.1...
       1.88, 1.89, 1.9 , 1.91, 1.92, 1.93, 1.94, 1.95, 1.96, 1.97, 1.98,
       1.99]),
                                        'fit_intercept': [True, False],
                                        'max_iter': [10, 100, 1000, 10000,
                                                     100000],
                                        'precompute': [True, False],
                                        'random_state': array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
                                        'selection': ['random', 'cyclic'],
                                        'warm_start': [True, False]},
                   pre_dispatch='2*n_jobs', random_state=41, refit=True,
                   return_train_score=False, scoring=None, verbose=2)

In [55]:
las_random.best_params_

{'warm_start': False,
 'selection': 'cyclic',
 'random_state': 22,
 'precompute': False,
 'max_iter': 100,
 'fit_intercept': True,
 'alpha': 1.01}

In [56]:
## lasso with default hyperparameters

base_las = Lasso()
base_las.fit(xtrklaos, ytrklaos)
base_las_accuracy = evaluate(base_rdg, xtsklaos, ytsklaos)

Model Performance
Average Error: 7.2924 degrees.
Accuracy = 99.9119%.
RMSE = 11.8251
R2 Score = 0.9978.

In [57]:
## Lasso with best hyperparameters

best_las = las_random.best_estimator_
best_las.fit(xtrklaos, ytrklaos)
best_las_accuracy = evaluate(best_las, xtsklaos, ytsklaos)

Model Performance
Average Error: 7.2938 degrees.
Accuracy = 99.9119%.
RMSE = 11.8258
R2 Score = 0.9978.

## ElasticNet

In [58]:
elas_random.fit(xtrklaos, ytrklaos)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.

Fitting 5 folds for each of 100 candidates, totalling 500 fits

[Parallel(n_jobs=-1)]: Done 500 out of 500 | elapsed:    0.4s finished

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=ElasticNet(alpha=1.0, copy_X=True,
                                        fit_intercept=True, l1_ratio=0.5,
                                        max_iter=1000, normalize=False,
                                        positive=False, precompute=False,
                                        random_state=None, selection='cyclic',
                                        tol=0.0001, warm_start=False),
                   iid='deprecated', n_iter=100, n_jobs=-1,
                   param_distributions={'alpha': array([1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06,...
       0.87, 0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97,
       0.98, 0.99]),
                                        'max_iter': [10, 100, 1000, 10000,
                                                     100000],
                                        'positive': [True, False],
                                        'precompute': [True, False],
                                        'random_state': array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
                                        'selection': ['random', 'cyclic'],
                                        'warm_start': [True, False]},
                   pre_dispatch='2*n_jobs', random_state=41, refit=True,
                   return_train_score=False, scoring=None, verbose=2)

In [59]:
elas_random.best_params_

{'warm_start': True,
 'selection': 'cyclic',
 'random_state': 21,
 'precompute': False,
 'positive': False,
 'max_iter': 1000,
 'l1_ratio': 0.5499999999999998,
 'fit_intercept': True,
 'alpha': 1.0}

In [60]:
## elasticnet with default hyperparameters
base_elas = ElasticNet()
base_elas.fit(xtrklaos, ytrklaos)
base_elas_accuracy = evaluate(base_elas, xtsklaos, ytsklaos)

Model Performance
Average Error: 7.2938 degrees.
Accuracy = 99.9119%.
RMSE = 11.8258
R2 Score = 0.9978.

In [61]:
## elasticnet with best hyperparameters

best_elas = elas_random.best_estimator_
best_elas.fit(xtrklaos, ytrklaos)
best_elas_accuracy = evaluate(best_elas, xtsklaos, ytsklaos)

Model Performance
Average Error: 7.2938 degrees.
Accuracy = 99.9119%.
RMSE = 11.8258
R2 Score = 0.9978.

In [62]:
## LinearRegression with default best hyperparameters
print('best linear:')
best_lnr = lnr_random.best_estimator_
best_lnr.fit(xtrklaos, ytrklaos)
best_lnr_accuracy = evaluate(best_lnr, xtrklaos, ytrklaos)

## Ridge with best hyperparameters
print('best ridge:')
best_rdg = rdg_random.best_estimator_
best_rdg.fit(xtrklaos, ytrklaos)
best_rdg_accuracy = evaluate(best_rdg, xtrklaos, ytrklaos)


## Lasso with best hyperparameters
print('best lasso:')
best_las = las_random.best_estimator_
best_las.fit(xtrklaos, ytrklaos)
best_las_accuracy = evaluate(best_las, xtsklaos, ytsklaos)


## elasticnet with best hyperparameters
print('best elastic:')
best_elas = elas_random.best_estimator_
best_elas.fit(xtrklaos, ytrklaos)
best_elas_accuracy = evaluate(best_elas, xtsklaos, ytsklaos)

best linear:
Model Performance
Average Error: 7.2497 degrees.
Accuracy = 99.9122%.
RMSE = 11.9905
R2 Score = 0.9974.
best ridge:
Model Performance
Average Error: 7.2849 degrees.
Accuracy = 99.9118%.
RMSE = 11.9916
R2 Score = 0.9974.
best lasso:
Model Performance
Average Error: 7.2938 degrees.
Accuracy = 99.9119%.
RMSE = 11.8258
R2 Score = 0.9978.
best elastic:
Model Performance
Average Error: 7.2938 degrees.
Accuracy = 99.9119%.
RMSE = 11.8258
R2 Score = 0.9978.

In [63]:
#create and train the linear regression model
ri = best_rdg
# {'normalize': True, 'n_jobs': 'int', 'fit_intercept': False, 'copy_X': True}
#train the model {'normalize': True, 'fit_intercept': False}
lr.fit(xtrklaos, ytrklaos)

import joblib
joblib.dump(lr,'regressionlaos')

jm = joblib.load('regressionlaos')
jm

LinearRegression(copy_X=True, fit_intercept=False, n_jobs='int', normalize=True)

In [64]:
klaos = (input('kurs: ')).split(',')
kulaos1 = []
for i in klaos:
    a  = float(i)
    kulaos1.append(a)
kulaos1 = np.array(kulaos1)
if kulaos1.shape[0] == 1:
    kulaos = kulaos1.reshape(1,1)
else:
    kulaos = np.array(kulaos1).reshape(-1,1)

kulaos1

kurs: 22000,22500

array([22000., 22500.])

In [65]:
kurslaos = jm.predict(kulaos)
# hasil = kurslaos / np.array([5])
# hasil
kurslaos

array([22000.84494055, 22500.86414375])

In [70]:
x = (input('insert: ')).split(',')
# x = np.array(x)
q = []
for i in range(len(x)):
    c = float(x[i])
#     d = c / kurslaos[i]
    q.append(c)
q = np.array(q)

if len(q) == len(kurslaos):
    divide = q / kulaos1
    print(divide)
    if divide.shape[0] == 1:
        divide = divide.reshape(1,1)
        ylr = im.predict(divide)
        ylr
        ylrcon = ylr * kurslaos
        ylrcon
        conawal = q/kulaos1
        returncona = []
        for i in range(len(ylr)):
            returncon = (ylr[i]-conawal[i])/conawal[i]
            returncona.append(returncon)
        
    else:
        divide = np.array(divide).reshape(-1,1)
        ylr = im.predict(divide)
        ylr
        ylrcon = ylr * kurslaos
        ylrcon
        conawal = q/kulaos1
        returncona = []
        for i in range(len(ylr)):
            returncon = (ylr[i]-conawal[i])/conawal[i]
            returncona.append(returncon)

else:
#     print('length should be the same')
    divide = 'length should be the same'
    ylr = divide
    ylrcon = divide
    conawal = divide
    returncona = []
    for i in range(len(ylr)):
        returncon = (ylr[i]-conawal[i])/conawal[i]
        returncona.append(returncon)

print(returncona)
ylrcon

insert: 700,709
[0.03181818 0.03151111]
[-0.0007344169146990464, -0.0007344169146990318]

array([699.51277289, 708.50650854])